/**
 * خريطة التسميات العربية لنظام ERP Pro
 *
 * يحتوي هذا الملف على خرائط شاملة لترجمة أسماء أنواع المستندات
 * وأسماء الحسابات من الإنجليزية إلى العربية، بالإضافة إلى دوال
 * مساعدة للترجمة مع احتياطي للأسماء غير الموجودة.
 */

// ---------------------------------------------------------------------------
// أنواع المستندات (DocType Labels)
// ---------------------------------------------------------------------------

export const DOCTYPE_LABELS: Record<string, string> = {
  'Account': 'حساب',
  'Journal Entry': 'قيد يومية',
  'Payment Entry': 'سند دفع',
  'Sales Invoice': 'فاتورة مبيعات',
  'Purchase Invoice': 'فاتورة مشتريات',
  'Sales Order': 'أمر بيع',
  'Purchase Order': 'أمر شراء',
  'Quotation': 'عرض سعر',
  'Delivery Note': 'إشعار تسليم',
  'Customer': 'عميل',
  'Supplier': 'مورد',
  'Item': 'صنف',
  'Warehouse': 'مستودع',
  'Employee': 'موظف',
  'Attendance': 'حضور',
  'Leave Application': 'طلب إجازة',
  'Salary Slip': 'كشف راتب',
  'Salary Structure': 'هيكل راتب',
  'Cost Center': 'مركز تكلفة',
  'Fiscal Year': 'سنة مالية',
  'Branch': 'فرع',
  'Asset': 'أصل',
  'Asset Category': 'فئة أصل',
  'Depreciation Schedule': 'جدول الإهلاك',
  'Stock Entry': 'حركة مخزون',
  'Stock Reconciliation': 'جرد مخزون',
  'Bin': 'رصيد مخزون',
  'Price List': 'قائمة أسعار',
  'Mode of Payment': 'طريقة الدفع',
  'Company': 'شركة',
  'Lead': 'عميل محتمل',
  'Opportunity': 'فرصة',
  'Communication': 'اتصال',
  'ToDo': 'مهمة',
  'Event': 'حدث',
  'Subscription': 'اشتراك',
  'Loyalty Program': 'برنامج ولاء',
  'Contract': 'عقد',
  'Auto Repeat': 'تكرار تلقائي',
  'Material Request': 'طلب مواد',
  'Request for Quotation': 'طلب عروض أسعار',
  'Supplier Quotation': 'عرض سعر مورد',
  'Purchase Receipt': 'إستلام مشتريات',
  'Payment Entry Reference': 'مرجع الدفع',
  'Expense Claim': 'مطالبة مصروفات',
  'GL Entry': 'قيد دفتر الأستاذ',
  'POS Invoice': 'فاتورة نقطة بيع',
  'POS Profile': 'ملف نقطة البيع',
  'POS Opening Entry': 'فتح وردية',
  'POS Closing Entry': 'إغلاق وردية',
  'Period Closing Voucher': 'سند إقفال فترة',
  'Cheque Book': 'دفتر شيكات',
  'BOM': 'قائمة مواد',
  'Work Order': 'أمر عمل',
  'Workstation': 'محطة عمل',
  'Production Plan': 'خطة إنتاج',
  'Landed Cost Voucher': 'سند تكاليف إضافية',
  'Shift Type': 'نوع وردية',
  'Leave Type': 'نوع إجازة',
  'Leave Policy': 'سياسة إجازات',
  'Holiday List': 'قائمة عطلات',
  'Payroll Entry': 'مسير رواتب',
  'Employee Advance': 'سلفة موظف',
  'Loan': 'قرض',
  'File': 'ملف',
  'Workflow': 'سير عمل',
  'Timesheet': 'جدول أوقات',
  'Tax Category': 'فئة ضريبية',
  'Tax Template': 'قالب ضريبي',
  'Item Price': 'سعر الصنف',
  'Stock Ledger Entry': 'حركة مخزون',
  'Employee Contract': 'عقد موظف',
  'Notification Log': 'سجل إشعارات',
  'Bank Account': 'حساب بنكي',
  'Recurring Journal Entry': 'قيد يومية متكرر',
  'Journal Entry Template': 'قالب قيد يومي',
  'Sales Taxes and Charges Template': 'قالب ضرائب المبيعات',
  'Purchase Taxes and Charges Template': 'قالب ضرائب المشتريات',
  'Customer Group': 'مجموعة عملاء',
  'Supplier Group': 'مجموعة موردين',
  'Territory': 'منطقة',
  'Item Group': 'مجموعة أصناف',
  'Brand': 'علامة تجارية',
  'Item Variant': 'متغير صنف',
  'Item Attribute': 'سمة صنف',
  'UOM': 'وحدة قياس',
  'Stock Settings': 'إعدادات المخزون',
  'Accounts Settings': 'إعدادات الحسابات',
  'HR Settings': 'إعدادات الموارد البشرية',
  'Buying Settings': 'إعدادات المشتريات',
  'Selling Settings': 'إعدادات المبيعات',
  'POS Settings': 'إعدادات نقطة البيع',
  'Print Format': 'تنسيق طباعة',
  'Letter Head': 'رأس رسالة',
  'Email Account': 'حساب بريد',
  'SMS Settings': 'إعدادات الرسائل',
  'Custom Field': 'حقل مخصص',
  'Property Setter': 'مُعيِّن خاصية',
  'Authorization Rule': 'قاعدة تفويض',
  'Workflow Action': 'إجراء سير عمل',
  // ── أنواع مستندات إضافية ──────────────────────────────────────────────
  'Sales Partner': 'شريك مبيعات',
  'Sales Person': 'مندوب مبيعات',
  'Sales Team': 'فريق مبيعات',
  'Campaign': 'حملة',
  'Pricing Rule': 'قاعدة تسعير',
  'Promotional Scheme': 'مخطط ترويجي',
  'Shipping Rule': 'قاعدة شحن',
  'Authorization Control': 'تحكم بالتفويض',
  'C Form': 'نموذج C',
  'Commission': 'عمولة',
  'Appointment': 'موعد',
  'Newsletter': 'نشرة إخبارية',
  'Email Group': 'مجموعة بريد',
  'Address': 'عنوان',
  'Contact': 'جهة اتصال',
  'Address Template': 'قالب عنوان',
  'Email Template': 'قالب بريد',
  'SMS Template': 'قالب رسالة',
  'Notification': 'إشعار',
  'Email Digest': 'ملخص بريد',
  'Auto Email Report': 'تقرير بريد تلقائي',
  'Report': 'تقرير',
  'Dashboard': 'لوحة معلومات',
  'Dashboard Chart': 'رسم بياني',
  'Number Card': 'بطاقة رقمية',
  'Module Def': 'تعريف وحدة',
  'DocType': 'نوع مستند',
  'Page': 'صفحة',
  'Role': 'دور',
  'User': 'مستخدم',
  'Permission': 'صلاحية',
  'Bulk Update': 'تحديث جماعي',
  'Data Import': 'استيراد بيانات',
  'Version': 'إصدار',
  'Comment': 'تعليق',
  'Tag': 'وسم',
  'Note': 'ملاحظة',
  'Vehicle': 'مركبة',
  'Vehicle Log': 'سجل مركبة',
  'Driver': 'سائق',
  'Transporter': 'ناقل',
  'Batch': 'دفعة',
  'Serial No': 'رقم تسلسلي',
  'Installation Note': 'ملاحظة تركيب',
  'Project': 'مشروع',
  'Task': 'مهمة',
  'Timesheet Detail': 'تفصيل جدول أوقات',
  'Activity Cost': 'تكلفة نشاط',
  'Issue': 'بلاغ',
  'Warranty Claim': 'مطالبة ضمان',
  'Service Level Agreement': 'اتفاقية مستوى الخدمة',
  'Maintenance Visit': 'زيارة صيانة',
  'Maintenance Schedule': 'جدول صيانة',
  'Quality Inspection': 'فحص جودة',
  'Quality Goal': 'هدف جودة',
  'Quality Feedback': 'ملاحظات جودة',
  'Compensation': 'تعويض',
  'Salary Component': 'عنصر راتب',
  'Income Tax Slab': 'شريحة ضريبة الدخل',
  'Tax Rule': 'قاعدة ضريبية',
  'Tax Withholding Category': 'فئة حجز ضريبي',
  'Fee Schedule': 'جدول رسوم',
  'Fee Structure': 'هيكل رسوم',
  'Fee Category': 'فئة رسوم',
  'Student': 'طالب',
  'Program': 'برنامج',
  'Course': 'دورة',
  'Instructor': 'مدرب',
  'Room': 'غرفة',
  'Student Group': 'مجموعة طلاب',
  'Student Batch': 'دفعة طلاب',
  'Assessment': 'تقييم',
  'Grading Scale': 'مقياس درجات',
  'Evaluation': 'تقييم أداء',
  'Appraisal': 'تقييم موظف',
  'Appraisal Template': 'قالب تقييم',
  'Goal': 'هدف',
  'KRA': 'مؤشر أداء رئيسي',
  'Feedback': 'ملاحظات',
  'Training Program': 'برنامج تدريبي',
  'Training Event': 'فعالية تدريبية',
  'Training Result': 'نتيجة تدريب',
  'Training Feedback': 'ملاحظات تدريب',
  'Employee Grievance': 'شكوى موظف',
  'Employee Onboarding': 'استقدام موظف',
  'Employee Separation': 'مغادرة موظف',
  'Employee Transfer': 'نقل موظف',
  'Employee Promotion': 'ترقية موظف',
  'Employee Referral': 'إحالة موظف',
  'Job Opening': 'وظيفة شاغرة',
  'Job Applicant': 'متقدم لوظيفة',
  'Job Offer': 'عرض وظيفة',
  'Staffing Plan': 'خطة توظيف',
  'Interview': 'مقابلة',
  'Offer Term': 'شرط عرض',
  'Expense Approval': 'موافقة مصروفات',
  'Travel Request': 'طلب سفر',
  'Expense Claim Detail': 'تفصيل مطالبة مصروفات',
  'Expense Claim Type': 'نوع مطالبة مصروفات',
  'Crop': 'محصول',
  'Land Unit': 'وحدة أرض',
  'Agricultultural Task': 'مهمة زراعية',
  'Disease': 'مرض',
  'Fertilizer': 'سماد',
  'Soil Analysis': 'تحليل تربة',
  'Water Analysis': 'تحليل ماء',
  'Plant Analysis': 'تحليل نبات',
};

// ---------------------------------------------------------------------------
// أسماء الحسابات (Account Name Map)
// ---------------------------------------------------------------------------

export const ACCOUNT_NAME_MAP: Record<string, string> = {
  // ── الأصول (Asset) ──────────────────────────────────────────────────────
  'Application of Funds': 'تطبيق الأموال',
  'Current Assets': 'الأصول المتداولة',
  'Cash In Hand': 'النقدية بالخزينة',
  'Cash': 'النقدية',
  'Bank Accounts': 'الحسابات البنكية',
  'Petty Cash': 'الصندوق النقدي',
  'Receivables': 'المدينون',
  'Accounts Receivable': 'الذمم المدينة',
  'Debtors': 'المدينون',
  'Creditors': 'الدائنون',
  'Stock Assets': 'أصول المخزون',
  'Stock In Hand': 'المخزون تحت اليد',
  'Stock Received But Not Billed': 'مخزون مستلم غير مفوتر',
  'Tax Assets': 'أصول ضريبية',
  'Taxes and Charges Receivable': 'ضرائب ورسوم مستحقة القبض',
  'Cost of Goods Sold Account': 'حساب تكلفة البضاعة المباعة',
  'Fixed Assets': 'الأصول الثابتة',
  'Capital Equipment': 'المعدات الرأسمالية',
  'Computers': 'حواسيب',
  'Furniture and Fixture': 'الأثاث والتجهيزات',
  'Office Equipment': 'معدات مكتبية',
  'Plant and Machinery': 'الآلات والمعدات',
  'Buildings': 'مباني',
  'Accumulated Depreciation': 'الإهلاك المتراكم',
  'CWIP Account': 'حساب الأصول تحت التنفيذ',
  'Temporary Accounts': 'حسابات مؤقتة',
  'Suspense Account': 'حساب معلق',
  'Bank Overdraft': 'سحب بنكي مكشوف',
  'Cash Credit': 'ائتمان نقدي',

  // ── الخصوم (Liability) ─────────────────────────────────────────────────
  'Sources of Funds': 'مصادر الأموال',
  'Source of Funds': 'مصدر الأموال',
  'Current Liabilities': 'الخصوم المتداولة',
  'Accounts Payable': 'الذمم الدائنة',
  'Payables': 'الدائنون',
  'Stock Liabilities': 'التزامات المخزون',
  'Stock Received But Not Billed - Liabilities': 'مخزون مستلم غير مفوتر - التزامات',
  'Tax Liabilities': 'التزامات ضريبية',
  'Taxes and Charges Payable': 'ضرائب ورسوم مستحقة الدفع',
  'Statutory Liabilities': 'التزامات قانونية',
  'Long Term Liabilities': 'التزامات طويلة الأجل',
  'Secured Loans': 'قروض مضمونة',
  'Unsecured Loans': 'قروض غير مضمونة',
  'Bank Loans': 'قروض بنكية',
  'Loan Account': 'حساب القرض',
  'Capital Account': 'حساب رأس المال',
  'Shareholders Funds': 'أموال المساهمين',
  'Share Capital': 'رأس المال',
  'Reserves and Surplus': 'الاحتياطيات والفائض',
  'Retained Earnings': 'الأرباح المحتجزة',
  'Accumulated Profit': 'الأرباح المتراكمة',
  'Opening Balance Equity': 'رصيد افتتاحي حقوق الملكية',
  'Dividend Payable': 'أرباح مستحقة الدفع',
  'Equity': 'حقوق الملكية',
  'Provision': 'مخصصات',

  // ── الإيرادات (Income) ─────────────────────────────────────────────────
  'Income': 'الإيرادات',
  'Direct Income': 'الإيرادات المباشرة',
  'Sales Account': 'حساب المبيعات',
  'Sales': 'المبيعات',
  'Service': 'خدمات',
  'Indirect Income': 'الإيرادات غير المباشرة',
  'Commission Income': 'عمولات محصلة',
  'Interest Income': 'فوائد محصلة',
  'Other Income': 'إيرادات أخرى',
  'Exchange Gain': 'أرباح عملة',
  'Miscellaneous Income': 'إيرادات متنوعة',
  'Tax': 'ضريبة',

  // ── المصروفات (Expense) ────────────────────────────────────────────────
  'Expenses': 'المصروفات',
  'Direct Expenses': 'المصروفات المباشرة',
  'Cost of Goods Sold': 'تكلفة البضاعة المباعة',
  'Stock Expenses': 'مصروفات المخزون',
  'Indirect Expenses': 'المصروفات غير المباشرة',
  'Administrative Expenses': 'مصروفات إدارية',
  'Communication Expenses': 'مصروفات اتصالات',
  'Depreciation': 'إهلاك',
  'Electricity Expenses': 'مصروفات كهرباء',
  'Freight and Forwarding': 'شحن وتوصيل',
  'Marketing Expenses': 'مصروفات تسويق',
  'Office Expenses': 'مصروفات مكتبية',
  'Postage and Courier': 'بريد وخدمات',
  'Printing and Stationery': 'طباعة وأدوات مكتبية',
  'Rent': 'إيجار',
  'Repairs and Maintenance': 'صيانة وإصلاحات',
  'Salary': 'رواتب',
  'Salary Deductions': 'خصومات الرواتب',
  'Staff Welfare': 'رعاية الموظفين',
  'Travel Expenses': 'مصروفات سفر',
  'Utility Expenses': 'مصروفات مرافق',
  'Insurance': 'تأمين',
  'Legal Expenses': 'مصروفات قانونية',
  'Audit Fees': 'رسوم تدقيق',
  'Bank Charges': 'رسوم بنكية',
  'Charity': 'تبرعات',
  'Entertainment': 'ترفيه',
  'Miscellaneous Expenses': 'مصروفات متنوعة',
  'Exchange Loss': 'خسائر عملة',
  'Commission Expense': 'مصروفات عمولات',
  'Discount Given': 'خصومات ممنوحة',
  'Discount Received': 'خصومات محصلة',
  'Discount': 'خصم',
  'Round Off': 'تقريب',
  'Write Off Account': 'حساب شطب',
  'Write Off': 'شطب',
  'Exchange Rate Difference': 'فروق أسعار الصرف',
  'Stock Adjustment': 'تسوية مخزون',

  // ── أنواع الحسابات والأصول التفصيلية ──────────────────────────────────
  'Electronic Equipment': 'معدات إلكترونية',
  'Electronic Equipments': 'المعدات الإلكترونية',
  'Vehicles': 'مركبات',
  'Software': 'برمجيات',
  'Softwares': 'البرمجيات',
  'Packing': 'تعبئة',
  'Utility': 'خدمات',
  'Marketing': 'تسويق',
  'Traveling': 'سفر',
  'Maintenance': 'صيانة',
  'Commission': 'عمولة',
  'Bank': 'بنك',
  'Outgoing': 'صادر',
  'Incoming': 'وارد',
  'Temporary': 'مؤقت',
  'Exchange Gain/Loss': 'أرباح/خسائر الصرف',
  'TDS': 'خصم ضريبة عند المصدر',
  'TCS': 'تحصيل ضريبة عند المصدر',
  'Advances': 'سلف',
  'Courier Charges': 'رسوم بريد',
  'Telephone': 'هاتف',
  'Telephone Expenses': 'مصروفات الهاتف',
  'Internet': 'إنترنت',
  'Electricity': 'كهرباء',
  'Water': 'مياه',
  'Printing and Stationary': 'طباعة وأدوات مكتبية',
  'Legal': 'قانوني',
  'Consultancy': 'استشارات',
  'Training': 'تدريب',
  'Recruitment': 'توظيف',
  'Hospitality': 'ضيافة',
  'Promotion': 'ترويج',
  'Advertising': 'إعلان',
  'Bad Debts': 'ديون معدومة',
  'Freight': 'شحن',
  'Custom Duty': 'رسوم جمركية',
  'Shipping': 'شحن بحري',
  'VAT': 'ضريبة القيمة المضافة',
  'Input VAT': 'ضريبة القيمة المضافة المدفوعة',
  'Output VAT': 'ضريبة القيمة المضافة المحصلة',

  // ── أسماء حسابات إضافية من ERPNext ────────────────────────────────────
  'Application of Funds (Assets)': 'استخدام الأموال (الأصول)',
  'Asset Received But Not Billed': 'أصل مستلم غير مفوتر',
  'Bank Overdraft Account': 'حساب السحب المكشوف',
  'Capital Equipments': 'المعدات الرأسمالية',
  'Capital Stock': 'رأس المال السهمي',
  'Commission on Sales': 'عمولة المبيعات',
  'Dividends Paid': 'أرباح موزعة',
  'Duties and Taxes': 'الرسوم والضرائب',
  'Earnest Money': 'العربون',
  'Employee Advances': 'سلف الموظفين',
  'Expenses Included In Asset Valuation': 'مصروفات مدرجة في تقييم الأصول',
  'Expenses Included In Valuation': 'مصروفات مدرجة في التقييم',
  'Freight and Forwarding Charges': 'رسوم الشحن والنقل',
  'Furnitures and Fixtures': 'الأثاث والتركيبات',
  'Gain/Loss on Asset Disposal': 'ربح/خسارة التخلص من الأصول',
  'Impairment': 'انخفاض القيمة',
  'Investments': 'الاستثمارات',
  'Loans (Liabilities)': 'القروض (التزامات)',
  'Loans and Advances (Assets)': 'القروض والسلف (أصول)',
  'Office Equipments': 'معدات مكتبية',
  'Office Maintenance Expenses': 'مصروفات صيانة المكاتب',
  'Office Rent': 'إيجار المكتب',
  'Payroll Payable': 'رواتب مستحقة الدفع',
  'Plants and Machineries': 'الآلات والمعدات',
  'Postal Expenses': 'مصروفات بريدية',
  'Print and Stationery': 'طباعة وأدوات مكتبية',
  'Revaluation Surplus': 'فائض إعادة التقييم',
  'Sales Expenses': 'مصروفات المبيعات',
  'Securities and Deposits': 'الأوراق المالية والودائع',
  'Source of Funds (Liabilities)': 'مصدر الأموال (الالتزامات)',
  'Temporary Opening': 'افتتاحي مؤقت',
  'ERP Pro — VAT Recoverable': 'ضريبة القيمة المضافة — مستحقة الاسترداد',
  'Insurance Expenses': 'مصروفات التأمين',
  'Commission Expenses': 'مصروفات العمولات',
  'Depreciation Expenses': 'مصروفات الإهلاك',
  'Unrealized Profit/Loss': 'أرباح/خسائر غير محققة',
  'Provision for Expenses': 'مخصص المصروفات',
  'Sundry Debtors': 'مدينون متنوعون',
  'Sundry Creditors': 'دائنون متنوعون',
  'General Reserve': 'الاحتياطي العام',
  'Share Premium': 'علاوة الإصدار',
  'Revenue Reserves': 'احتياطيات الإيرادات',
  'Trade Payables': 'دائنون تجاريون',
  'Trade Receivables': 'مدينون تجاريون',
  'Other Current Assets': 'أصول متداولة أخرى',
  'Other Current Liabilities': 'التزامات متداولة أخرى',
  'Other Non Current Assets': 'أصول غير متداولة أخرى',
  'Other Non Current Liabilities': 'التزامات غير متداولة أخرى',
  'Cost of Goods Manufactured': 'تكلفة البضاعة المصنعة',
  'Manufacturing Expenses': 'مصروفات التصنيع',
  'Service Income': 'إيرادات الخدمات',
  'Selling and Distribution Expenses': 'مصروفات بيع وتوزيع',
  'Financial Expenses': 'مصروفات مالية',
  'Tax Expenses': 'مصروفات ضريبية',
  'Net Profit': 'صافي الربح',
  'Gross Profit': 'إجمالي الربح',
  'Operating Profit': 'ربح التشغيل',
  'Profit Before Tax': 'الربح قبل الضريبة',
  'Profit After Tax': 'الربح بعد الضريبة',
  'Cash Flow from Operations': 'التدفق النقدي من العمليات',
  'Cash Flow from Investing': 'التدفق النقدي من الاستثمار',
  'Cash Flow from Financing': 'التدفق النقدي من التمويل',

  // ── أنواع الحسابات الشائعة مع لاحقة الشركة ───────────────────────────
  'Cash In Hand - شركة الأفق': 'النقدية بالخزينة - شركة الأفق',
  'Bank Accounts - شركة الأفق': 'الحسابات البنكية - شركة الأفق',
  'Debtors - شركة الأفق': 'المدينون - شركة الأفق',
  'Creditors - شركة الأفق': 'الدائنون - شركة الأفق',
  'Stock In Hand - شركة الأفق': 'المخزون تحت اليد - شركة الأفق',
  'Tax Assets - شركة الأفق': 'أصول ضريبية - شركة الأفق',
  'Fixed Assets - شركة الأفق': 'الأصول الثابتة - شركة الأفق',
  'Current Assets - شركة الأفق': 'الأصول المتداولة - شركة الأفق',
  'Current Liabilities - شركة الأفق': 'الخصوم المتداولة - شركة الأفق',
  'Application of Funds - شركة الأفق': 'تطبيق الأموال - شركة الأفق',
  'Source of Funds - شركة الأفق': 'مصدر الأموال - شركة الأفق',
  'Sources of Funds - شركة الأفق': 'مصادر الأموال - شركة الأفق',
  'Direct Income - شركة الأفق': 'الإيرادات المباشرة - شركة الأفق',
  'Direct Expenses - شركة الأفق': 'المصروفات المباشرة - شركة الأفق',
  'Indirect Income - شركة الأفق': 'الإيرادات غير المباشرة - شركة الأفق',
  'Indirect Expenses - شركة الأفق': 'المصروفات غير المباشرة - شركة الأفق',
  'Sales Account - شركة الأفق': 'حساب المبيعات - شركة الأفق',
  'Cost of Goods Sold - شركة الأفق': 'تكلفة البضاعة المباعة - شركة الأفق',
  'Capital Account - شركة الأفق': 'حساب رأس المال - شركة الأفق',
  'Reserves and Surplus - شركة الأفق': 'الاحتياطيات والفائض - شركة الأفق',
  'Retained Earnings - شركة الأفق': 'الأرباح المحتجزة - شركة الأفق',
  'Round Off - شركة الأفق': 'تقريب - شركة الأفق',
  'Stock Received But Not Billed - شركة الأفق': 'مخزون مستلم غير مفوتر - شركة الأفق',
  'Taxes and Charges Receivable - شركة الأفق': 'ضرائب مستحقة القبض - شركة الأفق',
  'Taxes and Charges Payable - شركة الأفق': 'ضرائب مستحقة الدفع - شركة الأفق',
  'Accumulated Depreciation - شركة الأفق': 'الإهلاك المتراكم - شركة الأفق',
  'Payable - شركة الأفق': 'مستحق دفع - شركة الأفق',
  'Receivable - شركة الأفق': 'مستحق قبض - شركة الأفق',
  'Unrealized Profit - شركة الأفق': 'أرباح غير محققة - شركة الأفق',
  'Unrealized Loss - شركة الأفق': 'خسائر غير محققة - شركة الأفق',
  'Advance Payment - شركة الأفق': 'دفعة مقدمة - شركة الأفق',
  'Advance - شركة الأفق': 'سلفة - شركة الأفق',
  'Provision - شركة الأفق': 'مخصصات - شركة الأفق',
  'Equity - شركة الأفق': 'حقوق الملكية - شركة الأفق',
  'Petty Cash - شركة الأفق': 'الصندوق النقدي - شركة الأفق',
  'Payables - شركة الأفق': 'الدائنون - شركة الأفق',
  'Receivables - شركة الأفق': 'المدينون - شركة الأفق',
  'Service - شركة الأفق': 'خدمات - شركة الأفق',
  'Tax - شركة الأفق': 'ضريبة - شركة الأفق',
  'Depreciation - شركة الأفق': 'إهلاك - شركة الأفق',
  'Salary - شركة الأفق': 'رواتب - شركة الأفق',
  'Rent - شركة الأفق': 'إيجار - شركة الأفق',
  'Insurance - شركة الأفق': 'تأمين - شركة الأفق',
  'Marketing - شركة الأفق': 'تسويق - شركة الأفق',
  'Write Off - شركة الأفق': 'شطب - شركة الأفق',
  'Stock Adjustment - شركة الأفق': 'تسوية مخزون - شركة الأفق',
  'Bank Charges - شركة الأفق': 'رسوم بنكية - شركة الأفق',
  'Discount - شركة الأفق': 'خصم - شركة الأفق',
  'Freight - شركة الأفق': 'شحن - شركة الأفق',
  'Custom Duty - شركة الأفق': 'رسوم جمركية - شركة الأفق',
  'Shipping - شركة الأفق': 'شحن بحري - شركة الأفق',

  // ── حسابات ERPNext إضافية شائعة قد لا تكون في الخريطة ──────────────
  'Account': 'حساب',
  'Accounts': 'حسابات',
  'Assets': 'الأصول',
  'Liabilities': 'الخصوم',
  'Expenses Included In Valuation - شركة الأفق': 'مصروفات مدرجة في التقييم - شركة الأفق',
  'Stock Received But Not Billed - Liabilities - شركة الأفق': 'مخزون مستلم غير مفوتر - التزامات - شركة الأفق',
  'Asset Received But Not Billed - شركة الأفق': 'أصل مستلم غير مفوتر - شركة الأفق',
  'CWIP Account - شركة الأفق': 'حساب الأصول تحت التنفيذ - شركة الأفق',
  'Gain/Loss on Asset Disposal - شركة الأفق': 'ربح/خسارة التخلص من الأصول - شركة الأفق',
  'Capital Equipments - شركة الأفق': 'المعدات الرأسمالية - شركة الأفق',
  'Computers - شركة الأفق': 'حواسيب - شركة الأفق',
  'Furniture and Fixture - شركة الأفق': 'الأثاث والتجهيزات - شركة الأفق',
  'Office Equipment - شركة الأفق': 'معدات مكتبية - شركة الأفق',
  'Plant and Machinery - شركة الأفق': 'الآلات والمعدات - شركة الأفق',
  'Buildings - شركة الأفق': 'مباني - شركة الأفق',
  'Vehicles - شركة الأفق': 'مركبات - شركة الأفق',
  'Electronic Equipment - شركة الأفق': 'معدات إلكترونية - شركة الأفق',
  'Software - شركة الأفق': 'برمجيات - شركة الأفق',
  'Investments - شركة الأفق': 'الاستثمارات - شركة الأفق',
  'Secured Loans - شركة الأفق': 'قروض مضمونة - شركة الأفق',
  'Unsecured Loans - شركة الأفق': 'قروض غير مضمونة - شركة الأفق',
  'Bank Loans - شركة الأفق': 'قروض بنكية - شركة الأفق',
  'Loan Account - شركة الأفق': 'حساب القرض - شركة الأفق',
  'Statutory Liabilities - شركة الأفق': 'التزامات قانونية - شركة الأفق',
  'Long Term Liabilities - شركة الأفق': 'التزامات طويلة الأجل - شركة الأفق',
  'Share Capital - شركة الأفق': 'رأس المال - شركة الأفق',
  'Opening Balance Equity - شركة الأفق': 'رصيد افتتاحي حقوق الملكية - شركة الأفق',
  'Dividend Payable - شركة الأفق': 'أرباح مستحقة الدفع - شركة الأفق',
  'General Reserve - شركة الأفق': 'الاحتياطي العام - شركة الأفق',
  'Share Premium - شركة الأفق': 'علاوة الإصدار - شركة الأفق',
  'Revenue Reserves - شركة الأفق': 'احتياطيات الإيرادات - شركة الأفق',
  'Trade Payables - شركة الأفق': 'دائنون تجاريون - شركة الأفق',
  'Trade Receivables - شركة الأفق': 'مدينون تجاريون - شركة الأفق',
  'Other Current Assets - شركة الأفق': 'أصول متداولة أخرى - شركة الأفق',
  'Other Current Liabilities - شركة الأفق': 'التزامات متداولة أخرى - شركة الأفق',
  'Other Non Current Assets - شركة الأفق': 'أصول غير متداولة أخرى - شركة الأفق',
  'Other Non Current Liabilities - شركة الأفق': 'التزامات غير متداولة أخرى - شركة الأفق',
  'Administrative Expenses - شركة الأفق': 'مصروفات إدارية - شركة الأفق',
  'Communication Expenses - شركة الأفق': 'مصروفات اتصالات - شركة الأفق',
  'Electricity Expenses - شركة الأفق': 'مصروفات كهرباء - شركة الأفق',
  'Freight and Forwarding - شركة الأفق': 'شحن وتوصيل - شركة الأفق',
  'Marketing Expenses - شركة الأفق': 'مصروفات تسويق - شركة الأفق',
  'Office Expenses - شركة الأفق': 'مصروفات مكتبية - شركة الأفق',
  'Postage and Courier - شركة الأفق': 'بريد وخدمات - شركة الأفق',
  'Printing and Stationery - شركة الأفق': 'طباعة وأدوات مكتبية - شركة الأفق',
  'Repairs and Maintenance - شركة الأفق': 'صيانة وإصلاحات - شركة الأفق',
  'Salary Deductions - شركة الأفق': 'خصومات الرواتب - شركة الأفق',
  'Staff Welfare - شركة الأفق': 'رعاية الموظفين - شركة الأفق',
  'Travel Expenses - شركة الأفق': 'مصروفات سفر - شركة الأفق',
  'Utility Expenses - شركة الأفق': 'مصروفات مرافق - شركة الأفق',
  'Legal Expenses - شركة الأفق': 'مصروفات قانونية - شركة الأفق',
  'Audit Fees - شركة الأفق': 'رسوم تدقيق - شركة الأفق',
  'Charity - شركة الأفق': 'تبرعات - شركة الأفق',
  'Entertainment - شركة الأفق': 'ترفيه - شركة الأفق',
  'Miscellaneous Expenses - شركة الأفق': 'مصروفات متنوعة - شركة الأفق',
  'Commission Income - شركة الأفق': 'عمولات محصلة - شركة الأفق',
  'Interest Income - شركة الأفق': 'فوائد محصلة - شركة الأفق',
  'Other Income - شركة الأفق': 'إيرادات أخرى - شركة الأفق',
  'Exchange Gain - شركة الأفق': 'أرباح عملة - شركة الأفق',
  'Miscellaneous Income - شركة الأفق': 'إيرادات متنوعة - شركة الأفق',
  'Sales - شركة الأفق': 'المبيعات - شركة الأفق',
  'Expenses - شركة الأفق': 'المصروفات - شركة الأفق',
  'Income - شركة الأفق': 'الإيرادات - شركة الأفق',
  'Stock Assets - شركة الأفق': 'أصول المخزون - شركة الأفق',
  'Stock Liabilities - شركة الأفق': 'التزامات المخزون - شركة الأفق',
  'Tax Liabilities - شركة الأفق': 'التزامات ضريبية - شركة الأفق',
  'Duties and Taxes - شركة الأفق': 'الرسوم والضرائب - شركة الأفق',
  'Suspense Account - شركة الأفق': 'حساب معلق - شركة الأفق',
  'Temporary Accounts - شركة الأفق': 'حسابات مؤقتة - شركة الأفق',
  'Bank Overdraft - شركة الأفق': 'سحب بنكي مكشوف - شركة الأفق',
  'Write Off Account - شركة الأفق': 'حساب شطب - شركة الأفق',
  'Exchange Rate Difference - شركة الأفق': 'فروق أسعار الصرف - شركة الأفق',
  'Unrealized Profit/Loss - شركة الأفق': 'أرباح/خسائر غير محققة - شركة الأفق',
  'Provision for Expenses - شركة الأفق': 'مخصص المصروفات - شركة الأفق',
  'Bad Debts - شركة الأفق': 'ديون معدومة - شركة الأفق',
  'Discount Given - شركة الأفق': 'خصومات ممنوحة - شركة الأفق',
  'Discount Received - شركة الأفق': 'خصومات محصلة - شركة الأفق',
  'Commission on Sales - شركة الأفق': 'عمولة المبيعات - شركة الأفق',
  'Sales Expenses - شركة الأفق': 'مصروفات المبيعات - شركة الأفق',
  'Office Rent - شركة الأفق': 'إيجار المكتب - شركة الأفق',
  'Office Maintenance Expenses - شركة الأفق': 'مصروفات صيانة المكاتب - شركة الأفق',
  'Insurance Expenses - شركة الأفق': 'مصروفات التأمين - شركة الأفق',
  'Commission Expenses - شركة الأفق': 'مصروفات العمولات - شركة الأفق',
  'Depreciation Expenses - شركة الأفق': 'مصروفات الإهلاك - شركة الأفق',
  'Manufacturing Expenses - شركة الأفق': 'مصروفات التصنيع - شركة الأفق',
  'Service Income - شركة الأفق': 'إيرادات الخدمات - شركة الأفق',
  'Selling and Distribution Expenses - شركة الأفق': 'مصروفات بيع وتوزيع - شركة الأفق',
  'Financial Expenses - شركة الأفق': 'مصروفات مالية - شركة الأفق',
  'Tax Expenses - شركة الأفق': 'مصروفات ضريبية - شركة الأفق',
  'Employee Advances - شركة الأفق': 'سلف الموظفين - شركة الأفق',
  'Earnest Money - شركة الأفق': 'العربون - شركة الأفق',
  'Dividends Paid - شركة الأفق': 'أرباح موزعة - شركة الأفق',
  'Expenses Included In Asset Valuation - شركة الأفق': 'مصروفات مدرجة في تقييم الأصول - شركة الأفق',
  'Freight and Forwarding Charges - شركة الأفق': 'رسوم الشحن والنقل - شركة الأفق',
  'Furnitures and Fixtures - شركة الأفق': 'الأثاث والتركيبات - شركة الأفق',
  'Office Equipments - شركة الأفق': 'معدات مكتبية - شركة الأفق',
  'Plants and Machineries - شركة الأفق': 'الآلات والمعدات - شركة الأفق',
  'Postal Expenses - شركة الأفق': 'مصروفات بريدية - شركة الأفق',
  'Print and Stationery - شركة الأفق': 'طباعة وأدوات مكتبية - شركة الأفق',
  'Revaluation Surplus - شركة الأفق': 'فائض إعادة التقييم - شركة الأفق',
  'Securities and Deposits - شركة الأفق': 'الأوراق المالية والودائع - شركة الأفق',
  'Capital Stock - شركة الأفق': 'رأس المال السهمي - شركة الأفق',
  'Loans (Liabilities) - شركة الأفق': 'القروض (التزامات) - شركة الأفق',
  'Loans and Advances (Assets) - شركة الأفق': 'القروض والسلف (أصول) - شركة الأفق',
  'Temporary Opening - شركة الأفق': 'افتتاحي مؤقت - شركة الأفق',
  'Impairment - شركة الأفق': 'انخفاض القيمة - شركة الأفق',
  'Cost of Goods Manufactured - شركة الأفق': 'تكلفة البضاعة المصنعة - شركة الأفق',
  'VAT - شركة الأفق': 'ضريبة القيمة المضافة - شركة الأفق',
  'Input VAT - شركة الأفق': 'ضريبة القيمة المضافة المدفوعة - شركة الأفق',
  'Output VAT - شركة الأفق': 'ضريبة القيمة المضافة المحصلة - شركة الأفق',
  'TDS - شركة الأفق': 'خصم ضريبة عند المصدر - شركة الأفق',
  'TCS - شركة الأفق': 'تحصيل ضريبة عند المصدر - شركة الأفق',
  'Sundry Debtors - شركة الأفق': 'مدينون متنوعون - شركة الأفق',
  'Sundry Creditors - شركة الأفق': 'دائنون متنوعون - شركة الأفق',
  'Bank Overdraft Account - شركة الأفق': 'حساب السحب المكشوف - شركة الأفق',
  'Cash Credit - شركة الأفق': 'ائتمان نقدي - شركة الأفق',
  'Capital Equipment - شركة الأفق': 'المعدات الرأسمالية - شركة الأفق',
  'Advances - شركة الأفق': 'سلف - شركة الأفق',
  'Courier Charges - شركة الأفق': 'رسوم بريد - شركة الأفق',
  'Telephone - شركة الأفق': 'هاتف - شركة الأفق',
  'Telephone Expenses - شركة الأفق': 'مصروفات الهاتف - شركة الأفق',
  'Internet - شركة الأفق': 'إنترنت - شركة الأفق',
  'Electricity - شركة الأفق': 'كهرباء - شركة الأفق',
  'Water - شركة الأفق': 'مياه - شركة الأفق',
  'Printing and Stationary - شركة الأفق': 'طباعة وأدوات مكتبية - شركة الأفق',
  'Legal - شركة الأفق': 'قانوني - شركة الأفق',
  'Consultancy - شركة الأفق': 'استشارات - شركة الأفق',
  'Training - شركة الأفق': 'تدريب - شركة الأفق',
  'Recruitment - شركة الأفق': 'توظيف - شركة الأفق',
  'Hospitality - شركة الأفق': 'ضيافة - شركة الأفق',
  'Promotion - شركة الأفق': 'ترويج - شركة الأفق',
  'Advertising - شركة الأفق': 'إعلان - شركة الأفق',
  'Exchange Gain/Loss - شركة الأفق': 'أرباح/خسائر الصرف - شركة الأفق',
  'Commission - شركة الأفق': 'عمولة - شركة الأفق',
  'Utility - شركة الأفق': 'خدمات - شركة الأفق',
  'Packing - شركة الأفق': 'تعبئة - شركة الأفق',
  'Traveling - شركة الأفق': 'سفر - شركة الأفق',
  'Maintenance - شركة الأفق': 'صيانة - شركة الأفق',
  'Outgoing - شركة الأفق': 'صادر - شركة الأفق',
  'Incoming - شركة الأفق': 'وارد - شركة الأفق',
  'Temporary - شركة الأفق': 'مؤقت - شركة الأفق',
  'Cash Flow from Operations - شركة الأفق': 'التدفق النقدي من العمليات - شركة الأفق',
  'Cash Flow from Investing - شركة الأفق': 'التدفق النقدي من الاستثمار - شركة الأفق',
  'Cash Flow from Financing - شركة الأفق': 'التدفق النقدي من التمويل - شركة الأفق',
  'Net Profit - شركة الأفق': 'صافي الربح - شركة الأفق',
  'Gross Profit - شركة الأفق': 'إجمالي الربح - شركة الأفق',
  'Operating Profit - شركة الأفق': 'ربح التشغيل - شركة الأفق',
  'Profit Before Tax - شركة الأفق': 'الربح قبل الضريبة - شركة الأفق',
  'Profit After Tax - شركة الأفق': 'الربح بعد الضريبة - شركة الأفق',

  // ── حسابات بأسماء شركات مختلفة (نمط عام) ───────────────────────────
  'Cash In Hand - SH': 'النقدية بالخزينة - SH',
  'Bank Accounts - SH': 'الحسابات البنكية - SH',
  'Debtors - SH': 'المدينون - SH',
  'Creditors - SH': 'الدائنون - SH',
  'Stock In Hand - SH': 'المخزون تحت اليد - SH',
  'Current Assets - SH': 'الأصول المتداولة - SH',
  'Current Liabilities - SH': 'الخصوم المتداولة - SH',
  'Application of Funds - SH': 'تطبيق الأموال - SH',
  'Source of Funds - SH': 'مصدر الأموال - SH',
  'Sources of Funds - SH': 'مصادر الأموال - SH',
  'Fixed Assets - SH': 'الأصول الثابتة - SH',
  'Direct Income - SH': 'الإيرادات المباشرة - SH',
  'Direct Expenses - SH': 'المصروفات المباشرة - SH',
  'Indirect Income - SH': 'الإيرادات غير المباشرة - SH',
  'Indirect Expenses - SH': 'المصروفات غير المباشرة - SH',
  'Sales Account - SH': 'حساب المبيعات - SH',
  'Capital Account - SH': 'حساب رأس المال - SH',
  'Reserves and Surplus - SH': 'الاحتياطيات والفائض - SH',
  'Retained Earnings - SH': 'الأرباح المحتجزة - SH',
  'Tax Assets - SH': 'أصول ضريبية - SH',
  'Tax Liabilities - SH': 'التزامات ضريبية - SH',
  'Payables - SH': 'الدائنون - SH',
  'Receivables - SH': 'المدينون - SH',
  'Equity - SH': 'حقوق الملكية - SH',
  'Cost of Goods Sold - SH': 'تكلفة البضاعة المباعة - SH',
  'Taxes and Charges Receivable - SH': 'ضرائب مستحقة القبض - SH',
  'Taxes and Charges Payable - SH': 'ضرائب مستحقة الدفع - SH',
  'Accumulated Depreciation - SH': 'الإهلاك المتراكم - SH',
  'Round Off - SH': 'تقريب - SH',
  'Depreciation - SH': 'إهلاك - SH',
  'Salary - SH': 'رواتب - SH',
  'Service - SH': 'خدمات - SH',
  'Tax - SH': 'ضريبة - SH',
  'Write Off - SH': 'شطب - SH',
  'Stock Adjustment - SH': 'تسوية مخزون - SH',
  'Bank Charges - SH': 'رسوم بنكية - SH',
  'Discount - SH': 'خصم - SH',
  'Freight - SH': 'شحن - SH',
  'Custom Duty - SH': 'رسوم جمركية - SH',
  'Shipping - SH': 'شحن بحري - SH',
  'Petty Cash - SH': 'الصندوق النقدي - SH',
  'Insurance - SH': 'تأمين - SH',
  'Marketing - SH': 'تسويق - SH',
  'Rent - SH': 'إيجار - SH',

  // ── حسابات بأسماء شركات CMP ─────────────────────────────────────────
  'Cash In Hand - CMP': 'النقدية بالخزينة - CMP',
  'Bank Accounts - CMP': 'الحسابات البنكية - CMP',
  'Debtors - CMP': 'المدينون - CMP',
  'Creditors - CMP': 'الدائنون - CMP',
  'Current Assets - CMP': 'الأصول المتداولة - CMP',
  'Current Liabilities - CMP': 'الخصوم المتداولة - CMP',
  'Application of Funds - CMP': 'تطبيق الأموال - CMP',
  'Source of Funds - CMP': 'مصدر الأموال - CMP',
  'Sources of Funds - CMP': 'مصادر الأموال - CMP',
  'Fixed Assets - CMP': 'الأصول الثابتة - CMP',
  'Direct Income - CMP': 'الإيرادات المباشرة - CMP',
  'Direct Expenses - CMP': 'المصروفات المباشرة - CMP',
  'Indirect Income - CMP': 'الإيرادات غير المباشرة - CMP',
  'Indirect Expenses - CMP': 'المصروفات غير المباشرة - CMP',
  'Sales Account - CMP': 'حساب المبيعات - CMP',
  'Capital Account - CMP': 'حساب رأس المال - CMP',
  'Reserves and Surplus - CMP': 'الاحتياطيات والفائض - CMP',
  'Retained Earnings - CMP': 'الأرباح المحتجزة - CMP',
  'Equity - CMP': 'حقوق الملكية - CMP',
  'Cost of Goods Sold - CMP': 'تكلفة البضاعة المباعة - CMP',
  'Stock In Hand - CMP': 'المخزون تحت اليد - CMP',
  'Tax Assets - CMP': 'أصول ضريبية - CMP',
  'Tax Liabilities - CMP': 'التزامات ضريبية - CMP',
  'Payables - CMP': 'الدائنون - CMP',
  'Receivables - CMP': 'المدينون - CMP',
  'Accumulated Depreciation - CMP': 'الإهلاك المتراكم - CMP',
  'Round Off - CMP': 'تقريب - CMP',
  'Depreciation - CMP': 'إهلاك - CMP',
  'Salary - CMP': 'رواتب - CMP',
  'Service - CMP': 'خدمات - CMP',
  'Tax - CMP': 'ضريبة - CMP',
  'Write Off - CMP': 'شطب - CMP',
  'Stock Adjustment - CMP': 'تسوية مخزون - CMP',
  'Bank Charges - CMP': 'رسوم بنكية - CMP',
  'Discount - CMP': 'خصم - CMP',
  'Freight - CMP': 'شحن - CMP',
  'Custom Duty - CMP': 'رسوم جمركية - CMP',
  'Shipping - CMP': 'شحن بحري - CMP',
  'Petty Cash - CMP': 'الصندوق النقدي - CMP',
  'Insurance - CMP': 'تأمين - CMP',
  'Marketing - CMP': 'تسويق - CMP',
  'Rent - CMP': 'إيجار - CMP',
};

// ---------------------------------------------------------------------------
// مصطلحات واجهة المستخدم الشائعة (UI Terms)
// ---------------------------------------------------------------------------

export const UI_TERMS: Record<string, string> = {
  'Draft': 'مسودة',
  'Submitted': 'مُقدَّم',
  'Cancelled': 'ملغى',
  'Approved': 'معتمد',
  'Rejected': 'مرفوض',
  'Pending': 'معلق',
  'Open': 'مفتوح',
  'Closed': 'مغلق',
  'Paid': 'مدفوع',
  'Unpaid': 'غير مدفوع',
  'Overdue': 'متأخر',
  'Partially Paid': 'مدفوع جزئياً',
  'Return': 'إرجاع',
  'Credit Note': 'إشعار دائن',
  'Debit Note': 'إشعار مدين',
  'Credit': 'دائن',
  'Debit': 'مدين',
  'Reconcile': 'تسوية',
  'Unreconcile': 'إلغاء تسوية',
  'Submit': 'تقديم',
  'Cancel': 'إلغاء',
  'Amend': 'تعديل',
  'Duplicate': 'تكرار',
  'Print': 'طباعة',
  'Email': 'بريد إلكتروني',
  'Save': 'حفظ',
  'Delete': 'حذف',
  'Edit': 'تعديل',
  'View': 'عرض',
  'Create': 'إنشاء',
  'Update': 'تحديث',
  'Refresh': 'تحديث البيانات',
  'Search': 'بحث',
  'Filter': 'فلتر',
  'Sort': 'ترتيب',
  'Export': 'تصدير',
  'Import': 'استيراد',
  'Download': 'تحميل',
  'Upload': 'رفع',
  'Attach': 'إرفاق',
  'New': 'جديد',
  'List': 'قائمة',
  'Report': 'تقرير',
  'Dashboard': 'لوحة المعلومات',
  'Settings': 'إعدادات',
  'Setup': 'إعداد',
  'Configuration': 'تهيئة',
  'Calendar': 'تقويم',
  'Timeline': 'خط زمني',
  'Activity': 'نشاط',
  'Comments': 'تعليقات',
  'Assign': 'تعيين',
  'Share': 'مشاركة',
  'Follow': 'متابعة',
  'Archive': 'أرشفة',
  'Restore': 'استعادة',
  'Trash': 'سلة المحذوفات',
  'Active': 'نشط',
  'Inactive': 'غير نشط',
  'Enabled': 'مفعّل',
  'Disabled': 'معطّل',
  'Yes': 'نعم',
  'No': 'لا',
  'Default': 'افتراضي',
  'Mandatory': 'إلزامي',
  'Optional': 'اختياري',
  'Read Only': 'قراءة فقط',
  'Hidden': 'مخفي',
  'Visible': 'مرئي',
  'Company': 'الشركة',
  'Branch': 'الفرع',
  'Department': 'القسم',
  'Designation': 'المسمى الوظيفي',
  'Grade': 'الدرجة',
  'Date': 'التاريخ',
  'Time': 'الوقت',
  'Amount': 'المبلغ',
  'Quantity': 'الكمية',
  'Rate': 'السعر',
  'Total': 'الإجمالي',
  'Subtotal': 'المجموع الفرعي',
  'Tax': 'الضريبة',
  'Discount': 'الخصم',
  'Net Total': 'صافي الإجمالي',
  'Grand Total': 'الإجمالي الكلي',
  'Balance': 'الرصيد',
  'Opening': 'افتتاحي',
  'Closing': 'ختامي',
  'Advance': 'سلفة',
  'Allocation': 'تخصيص',
  'Reference': 'مرجع',
  'Remarks': 'ملاحظات',
  'Description': 'الوصف',
  'Status': 'الحالة',
  'Priority': 'الأولوية',
  'Category': 'الفئة',
  'Type': 'النوع',
  'Name': 'الاسم',
  'Code': 'الرمز',
  'Number': 'الرقم',
  'Series': 'التسلسل',
  'Account': 'الحساب',
  'Cost Center': 'مركز التكلفة',
  'Project': 'المشروع',
  'Customer': 'العميل',
  'Supplier': 'المورد',
  'Item': 'الصنف',
  'Warehouse': 'المستودع',
  'Currency': 'العملة',
  'Exchange Rate': 'سعر الصرف',
  'Payment': 'الدفع',
  'Receipt': 'الإيصال',
  'Invoice': 'الفاتورة',
  'Order': 'الأمر',
  'Quotation': 'عرض السعر',
  'Delivery': 'التسليم',
  'Shipment': 'الشحنة',
  'Purchase': 'الشراء',
  'Sale': 'البيع',
  'Journal': 'اليومية',
  'Ledger': 'دفتر الأستاذ',
  'Trial Balance': 'ميزان المراجعة',
  'Balance Sheet': 'الميزانية العمومية',
  'Profit and Loss': 'الأرباح والخسائر',
  'Cash Flow': 'التدفق النقدي',
  'General Ledger': 'دفتر الأستاذ العام',
};

// ---------------------------------------------------------------------------
// دوال مساعدة للترجمة
// ---------------------------------------------------------------------------

const ARABIC_REGEX = /[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/;

function containsArabic(text: string): boolean {
  return ARABIC_REGEX.test(text);
}

export function translateDoctype(doctype: string): string {
  return DOCTYPE_LABELS[doctype] ?? doctype;
}

/**
 * يُرجع الاسم العربي للحساب المحدد.
 *
 * إذا كان الاسم يحتوي بالفعل على أحرف عربية، يتم إرجاعه كما هو
 * دون ترجمة مكررة. إذا لم يتم العثور على ترجمة، يتم إرجاع الاسم
 * الإنجليزي الأصلي كاحتياطي.
 */
export function translateAccountName(name: string): string {
  if (!name) return name;
  // إذا كان الاسم يحتوي على أحرف عربية، أرجعه كما هو
  if (containsArabic(name)) {
    return name;
  }
  // البحث المباشر في الخريطة
  if (ACCOUNT_NAME_MAP[name]) {
    return ACCOUNT_NAME_MAP[name];
  }
  // محاولة بدون لاحقة الشركة (مثل " - SH" أو " - CMP")
  const dashIdx = name.lastIndexOf(' - ');
  if (dashIdx > 0) {
    const baseName = name.substring(0, dashIdx);
    if (ACCOUNT_NAME_MAP[baseName]) {
      return ACCOUNT_NAME_MAP[baseName] + name.substring(dashIdx);
    }
  }
  return name;
}

/**
 * يُرجع التسمية العربية لنوع الحساب (account_type)
 */
export function translateAccountType(type: string): string {
  const map: Record<string, string> = {
    'Bank': 'بنك',
    'Cash': 'نقدية',
    'Receivable': 'مدينون',
    'Payable': 'دائنون',
    'Stock': 'مخزون',
    'Tax': 'ضريبة',
    'Fixed Asset': 'أصل ثابت',
    'Capital': 'رأس مال',
    'Expense': 'مصروفات',
    'Income': 'إيرادات',
    'Chargeable': 'قابل للشحن',
    'Temporary': 'مؤقت',
    'Equity': 'حقوق الملكية',
    'Depreciation': 'إهلاك',
    'Accumulated Depreciation': 'إهلاك متراكم',
    'Cash In Hand': 'النقدية بالخزينة',
    'Bank In Hand': 'الحسابات البنكية',
    'Outgoing': 'صادر',
    'Incoming': 'وارد',
  };
  return map[type] ?? type;
}

/**
 * يُرجع التسمية العربية لنوع الجذر (root_type)
 */
export function translateRootType(type: string): string {
  const map: Record<string, string> = {
    'Asset': 'أصول',
    'Liability': 'التزامات',
    'Income': 'إيرادات',
    'Expense': 'مصروفات',
    'Equity': 'حقوق الملكية',
  };
  return map[type] ?? type;
}

/**
 * يُرجع التسمية العربية لمصطلح واجهة المستخدم
 */
export function translateUITerm(term: string): string {
  return UI_TERMS[term] ?? term;
}

/**
 * يُرجع التسمية العربية لحالة المستند (docstatus)
 */
export function translateDocStatus(status: number): string {
  const map: Record<number, string> = {
    0: 'مسودة',
    1: 'مُقدَّم',
    2: 'ملغى',
  };
  return map[status] ?? 'غير معروف';
}
